if(NOT DEFINED SCGEOMETRY_BINARY_DIR OR NOT DEFINED SCGEOMETRY_CONSUMER_SOURCE_DIR
   OR NOT DEFINED SCGEOMETRY_VERIFY_ROOT OR NOT DEFINED SCGEOMETRY_CONFIG)
    message(FATAL_ERROR "Package-consumer verification requires build, source, root, and config variables.")
endif()

file(REMOVE_RECURSE "${SCGEOMETRY_VERIFY_ROOT}")
set(SCGEOMETRY_INSTALL_PREFIX "${SCGEOMETRY_VERIFY_ROOT}/install")
set(SCGEOMETRY_CONSUMER_BUILD_DIR "${SCGEOMETRY_VERIFY_ROOT}/consumer-build")

execute_process(
    COMMAND "${CMAKE_COMMAND}" --install "${SCGEOMETRY_BINARY_DIR}" --config "${SCGEOMETRY_CONFIG}"
            --prefix "${SCGEOMETRY_INSTALL_PREFIX}"
    RESULT_VARIABLE SCGEOMETRY_INSTALL_RESULT
)
if(NOT SCGEOMETRY_INSTALL_RESULT EQUAL 0)
    message(FATAL_ERROR "Installing SCGeometry for package-consumer verification failed.")
endif()

set(SCGEOMETRY_CONFIGURE_COMMAND
    "${CMAKE_COMMAND}" -S "${SCGEOMETRY_CONSUMER_SOURCE_DIR}" -B "${SCGEOMETRY_CONSUMER_BUILD_DIR}"
    "-DSCGeometry_DIR=${SCGEOMETRY_INSTALL_PREFIX}/Lib/cmake/SCGeometry"
)
if(DEFINED SCGEOMETRY_GENERATOR AND NOT SCGEOMETRY_GENERATOR STREQUAL "")
    list(APPEND SCGEOMETRY_CONFIGURE_COMMAND -G "${SCGEOMETRY_GENERATOR}")
endif()
if(DEFINED SCGEOMETRY_GENERATOR_PLATFORM AND NOT SCGEOMETRY_GENERATOR_PLATFORM STREQUAL "")
    list(APPEND SCGEOMETRY_CONFIGURE_COMMAND -A "${SCGEOMETRY_GENERATOR_PLATFORM}")
endif()

execute_process(COMMAND ${SCGEOMETRY_CONFIGURE_COMMAND} RESULT_VARIABLE SCGEOMETRY_CONFIGURE_RESULT)
if(NOT SCGEOMETRY_CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR "Configuring the installed package consumer failed.")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" --build "${SCGEOMETRY_CONSUMER_BUILD_DIR}" --config "${SCGEOMETRY_CONFIG}"
    RESULT_VARIABLE SCGEOMETRY_BUILD_RESULT
)
if(NOT SCGEOMETRY_BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR "Building the installed package consumer failed.")
endif()

file(GLOB SCGEOMETRY_RUNTIME_DIRS LIST_DIRECTORIES TRUE
    "${SCGEOMETRY_INSTALL_PREFIX}/Bin/*/${SCGEOMETRY_CONFIG}")
list(LENGTH SCGEOMETRY_RUNTIME_DIRS SCGEOMETRY_RUNTIME_DIR_COUNT)
if(NOT SCGEOMETRY_RUNTIME_DIR_COUNT EQUAL 1)
    message(FATAL_ERROR "Expected one installed SCGeometry runtime directory, found ${SCGEOMETRY_RUNTIME_DIR_COUNT}.")
endif()
list(GET SCGEOMETRY_RUNTIME_DIRS 0 SCGEOMETRY_RUNTIME_DIR)
set(SCGEOMETRY_CONSUMER_EXE "${SCGEOMETRY_CONSUMER_BUILD_DIR}/${SCGEOMETRY_CONFIG}/SCGeometryPackageConsumer${CMAKE_EXECUTABLE_SUFFIX}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "PATH=${SCGEOMETRY_RUNTIME_DIR};$ENV{PATH}" "${SCGEOMETRY_CONSUMER_EXE}"
    RESULT_VARIABLE SCGEOMETRY_RUN_RESULT
)
if(NOT SCGEOMETRY_RUN_RESULT EQUAL 0)
    message(FATAL_ERROR "Running the installed package consumer failed.")
endif()
