#include <gtest/gtest.h>

#include "Geometry.h"

using Geometry::SCLineSegment3d;
using Geometry::SCPlane;
using Geometry::SCPoint3d;
using Geometry::PolyhedronBody;
using Geometry::Section;
using Geometry::SCVector3d;

TEST(Section3dGapTest, NonPlanarDominantSectionGraphRemainsOpen)
{
    const PolyhedronBody body;
    const SCPlane cuttingPlane = SCPlane::FromPointAndNormal(SCPoint3d{0.0, 0.0, 0.1}, SCVector3d{0.0, 0.0, 1.0});

    const auto section = Section(body, cuttingPlane);
    (void)section;
    GTEST_SKIP() << "Known 3D gap: non-planar dominant section graph and ambiguous "
                    "non-manifold contour "
                    "stitching semantics in non-planar-dominant sections are still "
                    "open. "
                    "Covered subsets: convex-body oblique-face-to-face mid-plane "
                    "stitching (four-segment "
                    "closed-contour determinism on unit-cube y=0.5 cut), "
                    "triangular-prism mid-section (three-segment closed-contour "
                    "determinism, perimeter~=3), "
                    "triangular-prism mid-section on SCBrepBody path (three-segment "
                    "closed-contour determinism, "
                    "perimeter~=3), "
                    "unit-cube x-axis section (four-segment 1x1 square contour, "
                    "perimeter=4), "
                    "unit-cube x-axis section on SCBrepBody path (four-segment 1x1 square "
                    "contour, perimeter=4), "
                    "rectangular-prism z-axis section (four-segment 2x2 square contour, "
                    "perimeter=8), "
                    "rectangular-prism z-axis section on SCBrepBody path (four-segment "
                    "2x2 square contour, "
                    "perimeter=8), "
                    "rectangular-prism x-axis section on PolyhedronBody path "
                    "(four-segment 2x1 rectangle "
                    "contour, perimeter=6), "
                    "rectangular-prism x-axis section on SCBrepBody path (four-segment "
                    "2x1 rectangle contour, "
                    "perimeter=6), "
                    "unit-cube y-axis section on SCBrepBody path (four-segment 1x1 square "
                    "contour, perimeter=4), "
                    "rectangular-prism y-axis section on PolyhedronBody path "
                    "(four-segment 2x1 rectangle "
                    "contour, perimeter=6), "
                    "rectangular-prism y-axis section on SCBrepBody path (four-segment "
                    "2x1 rectangle contour, "
                    "perimeter=6), "
                    "unit-cube z-axis section on PolyhedronBody path (four-segment 1x1 "
                    "square contour, "
                    "perimeter=4), "
                    "unit-cube z-axis section on SCBrepBody path (four-segment 1x1 square "
                    "contour, perimeter=4), "
                    "mixed coplanar-frame + non-planar cube section on PolyhedronBody "
                    "path (2 polygons / 3 "
                    "closed contours / total area=9), "
                    "mixed coplanar-frame + non-planar cube section on SCBrepBody path (2 "
                    "polygons / 3 closed "
                    "contours / total area=9), "
                    "mixed closed-area + detached open-contour section on "
                    "PolyhedronBody path (1 polygon + 1 "
                    "open contour / mixed content), "
                    "and mixed closed-area + detached open-contour section on SCBrepBody "
                    "path (1 polygon + 1 open "
                    "contour / mixed content), "
                    "plus vertex-attached and edge-attached open-contour mixed-content "
                    "on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(1 polygon + 1 open contour / mixed content), "
                    "plus dual edge-attached open-contour mixed-content on "
                    "PolyhedronBody / SCBrepBody paths "
                    "(1 polygon + 2 open contours / mixed content), "
                    "plus mixed vertex-attached + edge-attached dual-open mixed-content "
                    "on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(1 polygon + 2 open contours / mixed content), "
                    "plus detached + vertex-attached + edge-attached triple-open "
                    "mixed-content on PolyhedronBody "
                    "/ SCBrepBody paths "
                    "(1 polygon + 3 open contours / mixed content), "
                    "and edge-adjacent plus strip-adjacent mixed coplanar + non-planar "
                    "area merge on "
                    "PolyhedronBody / SCBrepBody paths "
                    "(single merged polygon / area=2 or area=3 representative subsets), "
                    "plus strip-adjacent mixed area + detached open-contour arbitration "
                    "on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(1 polygon + 1 open contour / mixed content / area=3 "
                    "representative subset), "
                    "plus strip-adjacent mixed area + edge-attached open-contour "
                    "arbitration on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(1 polygon + 1 open contour / mixed content / area=3 "
                    "representative subset), "
                    "plus strip-adjacent mixed area + vertex-attached open-contour "
                    "arbitration on PolyhedronBody "
                    "/ SCBrepBody paths "
                    "(1 polygon + 1 open contour / mixed content / area=3 "
                    "representative subset), "
                    "plus strip-adjacent mixed area + vertex-attached + edge-attached "
                    "dual-open arbitration on "
                    "PolyhedronBody / SCBrepBody paths "
                    "(1 polygon + 2 open contours / mixed content / area=3 "
                    "representative subset), "
                    "plus strip-adjacent mixed area + detached + vertex-attached + "
                    "edge-attached triple-open "
                    "arbitration on PolyhedronBody / SCBrepBody paths "
                    "(1 polygon + 3 open contours / mixed content / area=3 "
                    "representative subset), "
                    "plus mixed detached-left + edge-attached open-contour ordering on "
                    "PolyhedronBody / SCBrepBody "
                    "paths "
                    "(boundary-attached contour sorts ahead of detached contour "
                    "representative subset), "
                    "plus detached + dual edge-attached mixed-content on PolyhedronBody "
                    "/ SCBrepBody paths "
                    "(1 polygon + 3 open contours representative subset), "
                    "plus mixed merged area with an interior hole on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(single polygon-with-hole / area=9 representative subset), "
                    "plus mixed merged polygon-with-hole + detached open contour on "
                    "PolyhedronBody / SCBrepBody "
                    "paths "
                    "(1 polygon-with-hole + 1 open contour representative subset), "
                    "plus mixed merged polygon-with-hole + edge-attached open contour "
                    "on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(1 polygon-with-hole + 1 open contour representative subset), "
                    "plus mixed merged polygon-with-hole + vertex-attached open contour "
                    "on PolyhedronBody / "
                    "SCBrepBody paths "
                    "(1 polygon-with-hole + 1 open contour representative subset), "
                    "and plus dual disjoint non-planar closed loops in the same section "
                    "plane on the "
                    "PolyhedronBody path "
                    "(2 polygons / 2 contours / 2 roots representative subset).";
}

TEST(Section3dGapTest, FaceMergeSemanticsAfterSectionRemainsOpen)
{
    const PolyhedronBody body;
    const SCPlane cuttingPlane = SCPlane::FromPointAndNormal(SCPoint3d{0.0, 0.0, 0.0}, SCVector3d{0.0, 0.0, 1.0});

    const auto section = Section(body, cuttingPlane);
    (void)section;
    GTEST_SKIP() << "Known 3D gap: section face-merge policy for ambiguous coplanar "
                    "fragments beyond adjacent "
                    "coplanar union subsets is not closed yet. "
                    "Covered subsets: two-face adjacent coplanar Polyhedron merge, "
                    "two-face adjacent coplanar "
                    "SCBrepBody merge, "
                    "three-face coplanar horizontal strip merge (3x1 rectangle, "
                    "area=3.0), three-face coplanar "
                    "horizontal strip merge on SCBrepBody path (area=3.0), "
                    "and four-face coplanar frame merge into a single polygon-with-hole "
                    "(area=8.0), "
                    "plus mixed frame-with-hole + adjacent non-planar area merge into "
                    "one polygon-with-hole "
                    "(area=9.0). "
                    "Remaining open: non-adjacent fragment merge across convex-hull "
                    "gaps, mixed open-curve/area "
                    "edge-adjacency arbitration beyond representative detached / "
                    "vertex-attached / edge-attached "
                    "/ detached-left-vs-edge-attached ordering / dual-edge-attached / "
                    "detached+dual-edge-attached / mixed vertex+edge-attached / "
                    "detached+vertex+edge-attached / "
                    "strip-adjacent-detached / strip-adjacent-edge-attached / "
                    "strip-adjacent-vertex-attached / "
                    "strip-adjacent-vertex+edge-attached / "
                    "strip-adjacent-detached+vertex+edge-attached subsets, "
                    "and more general mixed coplanar/non-planar adjacency arbitration "
                    "beyond the representative "
                    "edge-adjacent / strip-adjacent deterministic merge subsets.";
}

TEST(Section3dGapTest, MixedMergedAreaWithInteriorHoleAndDualBoundaryAttachedOpenContoursStillNeedArbitration)
{
    GTEST_SKIP() << "Known 3D gap: mixed coplanar/non-planar merged "
                    "polygon-with-hole now covers single "
                    "detached / edge-attached / vertex-attached outer-boundary "
                    "open-contour subsets, "
                    "but higher-order boundary-attached arbitration is still "
                    "open once multiple open "
                    "contours are present. "
                    "Representative unresolved scenario: a coplanar 3x3 "
                    "frame-with-hole (outer "
                    "[0,3]x[0,3], inner [1,2]x[1,2]) merged with an adjacent "
                    "non-planar area along the "
                    "outer boundary at z=0.5, "
                    "plus two extra open contours where one is edge-attached "
                    "on the merged outer "
                    "boundary and the other is vertex-attached at an adjacent "
                    "outer-boundary corner. "
                    "Expected future capability: preserve the single "
                    "polygon-with-hole and keep both "
                    "boundary-attached open contours separate with "
                    "deterministic ordering instead of "
                    "collapsing hole semantics or cross-stitching the spurs.";
}

